name: mcbroken
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  connectivity_plus: ^2.2.1
  go_router: ^3.0.6
  flutter_map: ^6.0.0
  http: ^1.1.0
  latlong2: ^0.9.0
  flutter_map_marker_cluster: ^1.3.0
  geolocator: ^10.0.0
  intl: ^0.18.0
  flutter_native_splash: ^2.2.16
  google_fonts: ^6.1.0
  flutter_map_location_marker: ^8.0.0
  equatable: ^2.0.5
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0


flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/mcbroken_icon_1024.png"
  image_path_ios: "assets/icons/mcbroken_icon_1024.png"

flutter_native_splash:
  color: "#2197f2"
  image: assets/mcbroken_big_text.png


flutter:


  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/